import { BlockItem, ProfileData, ThemeConfig } from "@/types/builder";

export const THEME_PRESETS: ThemeConfig[] = [
  {
    presetId: "midnight-emerald",
    name: "Midnight Emerald (Default)",
    bgType: "mesh",
    bgColor: "#070b09",
    bgGradient: "radial-gradient(ellipse at top, #062817 0%, #080d0b 60%, #030504 100%)",
    bgPattern: "none",
    buttonStyle: "rounded-xl",
    buttonHoverEffect: "glow",
    avatarStyle: "gradient-ring",
    socialStyle: "circle-buttons",
    cardFrameStyle: "glass-card",
    buttonBg: "#10b981",
    buttonTextColor: "#05130e",
    buttonBorderColor: "#10b98140",
    textColor: "#f0fdf4",
    subtextColor: "#6ee7b7",
    fontFamily: "jakarta",
    accentColor: "#10b981",
    cardOpacity: 90,
  },
  {
    presetId: "cyber-indigo",
    name: "Cyber Indigo",
    bgType: "mesh",
    bgColor: "#080816",
    bgGradient: "radial-gradient(ellipse at top, #1e1b4b 0%, #090919 60%, #04040a 100%)",
    bgPattern: "none",
    buttonStyle: "rounded-full",
    buttonHoverEffect: "scale",
    avatarStyle: "glow-badge",
    socialStyle: "pill-bar",
    cardFrameStyle: "glass-card",
    buttonBg: "#6366f1",
    buttonTextColor: "#ffffff",
    buttonBorderColor: "#818cf840",
    textColor: "#e0e7ff",
    subtextColor: "#a5b4fc",
    fontFamily: "space",
    accentColor: "#6366f1",
    cardOpacity: 85,
  },
  {
    presetId: "obsidian-minimal",
    name: "Obsidian Studio",
    bgType: "gradient",
    bgColor: "#0f0f11",
    bgGradient: "linear-gradient(180deg, #18181b 0%, #09090b 100%)",
    bgPattern: "none",
    buttonStyle: "glass",
    buttonHoverEffect: "lift",
    avatarStyle: "minimal",
    socialStyle: "circle-buttons",
    cardFrameStyle: "minimal-border",
    buttonBg: "rgba(255, 255, 255, 0.08)",
    buttonTextColor: "#ffffff",
    buttonBorderColor: "rgba(255, 255, 255, 0.15)",
    textColor: "#f4f4f5",
    subtextColor: "#a1a1aa",
    fontFamily: "inter",
    accentColor: "#e4e4e7",
    cardOpacity: 75,
  },
  {
    presetId: "neon-matrix",
    name: "Neon Matrix",
    bgType: "mesh",
    bgColor: "#040705",
    bgGradient: "radial-gradient(circle at 50% 0%, #052e16 0%, #020603 70%)",
    bgPattern: "grid",
    buttonStyle: "hard-shadow",
    buttonHoverEffect: "scale",
    avatarStyle: "glow-badge",
    socialStyle: "circle-buttons",
    cardFrameStyle: "glass-card",
    buttonBg: "#00ff66",
    buttonTextColor: "#000000",
    buttonBorderColor: "#00ff66",
    textColor: "#ecfdf5",
    subtextColor: "#34d399",
    fontFamily: "space",
    accentColor: "#00ff66",
    cardOpacity: 95,
  },
  {
    presetId: "sunset-glow",
    name: "Sunset Creative",
    bgType: "mesh",
    bgColor: "#140a12",
    bgGradient: "radial-gradient(ellipse at top, #4c0519 0%, #150811 60%, #080306 100%)",
    bgPattern: "none",
    buttonStyle: "rounded-2xl",
    buttonHoverEffect: "glow",
    avatarStyle: "gradient-ring",
    socialStyle: "pill-bar",
    cardFrameStyle: "glass-card",
    buttonBg: "#f43f5e",
    buttonTextColor: "#ffffff",
    buttonBorderColor: "#fb718544",
    textColor: "#fff1f2",
    subtextColor: "#fda4af",
    fontFamily: "outfit",
    accentColor: "#f43f5e",
    cardOpacity: 90,
  },
  {
    presetId: "clean-light",
    name: "Clean Light Canvas",
    bgType: "solid",
    bgColor: "#f8fafc",
    bgGradient: "linear-gradient(180deg, #ffffff 0%, #f1f5f9 100%)",
    bgPattern: "none",
    buttonStyle: "rounded-xl",
    buttonHoverEffect: "lift",
    avatarStyle: "minimal",
    socialStyle: "circle-buttons",
    cardFrameStyle: "minimal-border",
    buttonBg: "#0f172a",
    buttonTextColor: "#ffffff",
    buttonBorderColor: "#334155",
    textColor: "#0f172a",
    subtextColor: "#64748b",
    fontFamily: "jakarta",
    accentColor: "#0f172a",
    cardOpacity: 100,
  },
];

export const DEFAULT_PROFILE: ProfileData = {
  username: "sinergivisual",
  displayName: "Sinergi Visual",
  bio: "Creative Production & Video Agency. Kelola dan bagikan link portofolio serta aset digital kreatif Anda.",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
  verified: true,
  badgeText: "Verified Creative Studio",
  location: "Jakarta, Indonesia",
  socialLinks: [],
  showWatermark: true,
};

export const DEFAULT_BLOCKS: BlockItem[] = [];

export const BLOCK_TEMPLATES = [
  {
    type: "link" as const,
    title: "Link Kustom",
    description: "Tautkan ke website, portofolio eksternal, atau dokumen",
    icon: "Link2",
    accent: "from-emerald-500/20 to-teal-500/10 border-emerald-500/30 text-emerald-400",
    template: {
      title: "Kunjungi Website Baru Kami",
      url: "https://sinergivisual.com",
      subtitle: "Lihat karya terbaru dan layanan lengkap kami",
    },
  },
  {
    type: "product" as const,
    title: "Produk Digital & Aset",
    description: "Bagikan file LUTs, SFX, MOGRT, atau aset gratis dengan popup download",
    icon: "Sparkles",
    accent: "from-indigo-500/20 to-purple-500/10 border-indigo-500/30 text-indigo-400",
    template: {
      title: "Preset Warna & LUTs Pack Gratis",
      url: "#download-asset",
      subtitle: "Unduh file template secara instan",
      price: "FREE",
      originalPrice: "Rp 150.000",
      fileType: "ZIP • 35 MB",
      downloadUrl: "https://example.com/asset-download.zip",
      description: "Aset video editing berkualitas tinggi gratis untuk kebutuhan kreatif.",
      tags: ["Free Download", "High Quality"],
    },
  },
  {
    type: "video" as const,
    title: "Embed Video & Showreel",
    description: "Tampilkan video YouTube atau Vimeo langsung di halaman bio",
    icon: "PlayCircle",
    accent: "from-rose-500/20 to-orange-500/10 border-rose-500/30 text-rose-400",
    template: {
      title: "Video Showreel Terbaru",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      videoProvider: "youtube" as const,
      videoAspectRatio: "16:9" as const,
      subtitle: "Klik untuk memutar video langsung",
    },
  },
  {
    type: "header" as const,
    title: "Section Header",
    description: "Bagi halaman bio dengan judul kategori dan pembatas visual",
    icon: "Heading",
    accent: "from-amber-500/20 to-yellow-500/10 border-amber-500/30 text-amber-400",
    template: {
      title: "🔥 KATEGORI UTAMA",
      headerStyle: "accent" as const,
    },
  },
];
