import { BlockItem, ProfileData, ThemeConfig } from "@/types/builder";

export const THEME_PRESETS: ThemeConfig[] = [
  {
    presetId: "midnight-emerald",
    name: "Midnight Emerald (Default)",
    bgType: "mesh",
    bgColor: "#070b09",
    bgGradient: "radial-gradient(ellipse at top, #062817 0%, #080d0b 60%, #030504 100%)",
    bgPattern: "none",
    buttonStyle: "rounded-xl",
    buttonHoverEffect: "glow",
    avatarStyle: "gradient-ring",
    socialStyle: "circle-buttons",
    cardFrameStyle: "glass-card",
    buttonBg: "#10b981",
    buttonTextColor: "#05130e",
    buttonBorderColor: "#10b98140",
    textColor: "#f0fdf4",
    subtextColor: "#6ee7b7",
    fontFamily: "jakarta",
    accentColor: "#10b981",
    cardOpacity: 90,
  },
  {
    presetId: "cyber-indigo",
    name: "Cyber Indigo",
    bgType: "mesh",
    bgColor: "#080816",
    bgGradient: "radial-gradient(ellipse at top, #1e1b4b 0%, #090919 60%, #04040a 100%)",
    bgPattern: "none",
    buttonStyle: "rounded-full",
    buttonHoverEffect: "scale",
    avatarStyle: "glow-badge",
    socialStyle: "pill-bar",
    cardFrameStyle: "glass-card",
    buttonBg: "#6366f1",
    buttonTextColor: "#ffffff",
    buttonBorderColor: "#818cf840",
    textColor: "#e0e7ff",
    subtextColor: "#a5b4fc",
    fontFamily: "space",
    accentColor: "#6366f1",
    cardOpacity: 85,
  },
  {
    presetId: "obsidian-minimal",
    name: "Obsidian Studio",
    bgType: "gradient",
    bgColor: "#0f0f11",
    bgGradient: "linear-gradient(180deg, #18181b 0%, #09090b 100%)",
    bgPattern: "none",
    buttonStyle: "glass",
    buttonHoverEffect: "lift",
    avatarStyle: "minimal",
    socialStyle: "circle-buttons",
    cardFrameStyle: "minimal-border",
    buttonBg: "rgba(255, 255, 255, 0.08)",
    buttonTextColor: "#ffffff",
    buttonBorderColor: "rgba(255, 255, 255, 0.15)",
    textColor: "#f4f4f5",
    subtextColor: "#a1a1aa",
    fontFamily: "inter",
    accentColor: "#e4e4e7",
    cardOpacity: 75,
  },
  {
    presetId: "neon-matrix",
    name: "Neon Matrix",
    bgType: "mesh",
    bgColor: "#040705",
    bgGradient: "radial-gradient(circle at 50% 0%, #052e16 0%, #020603 70%)",
    bgPattern: "grid",
    buttonStyle: "hard-shadow",
    buttonHoverEffect: "scale",
    avatarStyle: "glow-badge",
    socialStyle: "circle-buttons",
    cardFrameStyle: "glass-card",
    buttonBg: "#00ff66",
    buttonTextColor: "#000000",
    buttonBorderColor: "#00ff66",
    textColor: "#ecfdf5",
    subtextColor: "#34d399",
    fontFamily: "space",
    accentColor: "#00ff66",
    cardOpacity: 95,
  },
  {
    presetId: "sunset-glow",
    name: "Sunset Creative",
    bgType: "mesh",
    bgColor: "#140a12",
    bgGradient: "radial-gradient(ellipse at top, #4c0519 0%, #150811 60%, #080306 100%)",
    bgPattern: "none",
    buttonStyle: "rounded-2xl",
    buttonHoverEffect: "glow",
    avatarStyle: "gradient-ring",
    socialStyle: "pill-bar",
    cardFrameStyle: "glass-card",
    buttonBg: "#f43f5e",
    buttonTextColor: "#ffffff",
    buttonBorderColor: "#fb718544",
    textColor: "#fff1f2",
    subtextColor: "#fda4af",
    fontFamily: "outfit",
    accentColor: "#f43f5e",
    cardOpacity: 90,
  },
  {
    presetId: "clean-light",
    name: "Clean Light Canvas",
    bgType: "solid",
    bgColor: "#f8fafc",
    bgGradient: "linear-gradient(180deg, #ffffff 0%, #f1f5f9 100%)",
    bgPattern: "none",
    buttonStyle: "rounded-xl",
    buttonHoverEffect: "lift",
    avatarStyle: "minimal",
    socialStyle: "circle-buttons",
    cardFrameStyle: "minimal-border",
    buttonBg: "#0f172a",
    buttonTextColor: "#ffffff",
    buttonBorderColor: "#334155",
    textColor: "#0f172a",
    subtextColor: "#64748b",
    fontFamily: "jakarta",
    accentColor: "#0f172a",
    cardOpacity: 100,
  },
];

export const DEFAULT_PROFILE: ProfileData = {
  username: "sinergivisual",
  displayName: "Sinergi Visual",
  bio: "Creative Production & Video Agency. Kami membagikan aset video editing, cinematic LUTs, template, dan link proyek internal tim.",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
  verified: true,
  badgeText: "Verified Creative Studio",
  location: "Jakarta, Indonesia",
  socialLinks: [
    { id: "soc-1", platform: "instagram", url: "https://instagram.com/sinergivisual", active: true },
    { id: "soc-2", platform: "youtube", url: "https://youtube.com/@sinergivisual", active: true },
    { id: "soc-3", platform: "behance", url: "https://behance.net/sinergivisual", active: true },
    { id: "soc-4", platform: "whatsapp", url: "https://wa.me/6281234567890", active: true },
    { id: "soc-5", platform: "tiktok", url: "https://tiktok.com/@sinergivisual", active: true },
  ],
  showWatermark: true,
};

export const DEFAULT_BLOCKS: BlockItem[] = [
  {
    id: "block-header-1",
    type: "header",
    title: "🎬 SHOWREEL & PORTOFOLIO",
    url: "",
    active: true,
    clicks: 0,
    headerStyle: "accent",
  },
  {
    id: "block-video-1",
    type: "video",
    title: "Official Showreel 2025 - Sinergi Visual",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoProvider: "youtube",
    videoAspectRatio: "16:9",
    active: true,
    clicks: 142,
    subtitle: "Tonton kompilasi proyek video commercial & music video terbaru kami",
  },
  {
    id: "block-link-1",
    type: "link",
    title: "Explore Behance Portfolio 2025",
    url: "https://behance.net/sinergivisual",
    subtitle: "Studi kasus visual identity, motion design, & 3D art",
    active: true,
    thumbnail: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=200&auto=format&fit=crop&q=80",
    icon: "FolderGit2",
    clicks: 389,
  },
  {
    id: "block-header-2",
    type: "header",
    title: "🎁 FREE DIGITAL ASSETS & TEMPLATES",
    url: "",
    active: true,
    clicks: 0,
    headerStyle: "divider",
  },
  {
    id: "block-prod-1",
    type: "product",
    title: "Cinematic Film LUTs Pack (Vol. 1)",
    url: "#download-luts",
    subtitle: "10 Preset Warna Hollywood (.CUBE) untuk Sony, Canon & BMPCC",
    price: "FREE",
    originalPrice: "Rp 249.000",
    fileType: "ZIP • 45 MB",
    downloadUrl: "https://drive.google.com/uc?export=download&id=cinematic-luts-vol1",
    description: "Koleksi 10 LUTs graded langsung oleh Sinergi Visual Colorist. Cocok untuk S-Log3, C-Log, V-Log, dan Rec.709. Mendukung Premiere Pro, DaVinci Resolve, & Final Cut Pro X.",
    thumbnail: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=300&auto=format&fit=crop&q=80",
    tags: ["Premiere Pro", "DaVinci Resolve", "FCPX", ".CUBE"],
    active: true,
    clicks: 890,
  },
  {
    id: "block-prod-2",
    type: "product",
    title: "Essential Video Sound FX (SFX) Master Pack",
    url: "#download-sfx",
    subtitle: "50+ Audio Riser, Whoosh, Sub Hit, & Cinematic Transitions (24bit WAV)",
    price: "FREE",
    originalPrice: "Rp 189.000",
    fileType: "ZIP • 180 MB",
    downloadUrl: "https://drive.google.com/uc?export=download&id=sfx-master-pack",
    description: "Asset sound design wajib untuk editor video modern. Kualitas studio 48kHz 24-bit WAV, bebas royalti untuk komersial maupun YouTube.",
    thumbnail: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&auto=format&fit=crop&q=80",
    tags: ["Sound FX", "24-Bit WAV", "Royalty Free"],
    active: true,
    clicks: 654,
  },
  {
    id: "block-prod-3",
    type: "product",
    title: "Premiere Pro Minimal Lower Thirds (.MOGRT)",
    url: "#download-mogrt",
    subtitle: "6 Template Title & Lower Third Animasi Minimalis Modern",
    price: "FREE",
    originalPrice: "Rp 129.000",
    fileType: "MOGRT • 15 MB",
    downloadUrl: "https://drive.google.com/uc?export=download&id=minimal-lower-thirds",
    description: "Template MOGRT siap pakai untuk Adobe Premiere Pro. Penggantian teks, warna font, dan durasi otomatis via Essential Graphics panel.",
    thumbnail: "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=300&auto=format&fit=crop&q=80",
    tags: ["Premiere Pro", "MOGRT", "Motion Graphics"],
    active: true,
    clicks: 432,
  },
  {
    id: "block-header-3",
    type: "header",
    title: "💬 KERJASAMA & HUBUNGI KAMI",
    url: "",
    active: true,
    clicks: 0,
    headerStyle: "simple",
  },
  {
    id: "block-link-2",
    type: "link",
    title: "Konsultasi & Diskusi Proyek Video (WhatsApp)",
    url: "https://wa.me/6281234567890?text=Halo%20Sinergi%20Visual,%20saya%20tertarik%20untuk%20diskusi%20proyek",
    subtitle: "Respon cepat tim produksi dalam 1x24 jam kerja",
    active: true,
    thumbnail: "https://images.unsplash.com/photo-1577563908411-5077b6dc7624?w=200&auto=format&fit=crop&q=80",
    icon: "MessageSquare",
    clicks: 215,
  },
];

export const BLOCK_TEMPLATES = [
  {
    type: "link" as const,
    title: "Link Kustom",
    description: "Tautkan ke website, portofolio eksternal, atau dokumen",
    icon: "Link2",
    accent: "from-emerald-500/20 to-teal-500/10 border-emerald-500/30 text-emerald-400",
    template: {
      title: "Kunjungi Website Baru Kami",
      url: "https://sinergivisual.com",
      subtitle: "Lihat karya terbaru dan layanan lengkap kami",
    },
  },
  {
    type: "product" as const,
    title: "Produk Digital & Aset",
    description: "Bagikan file LUTs, SFX, MOGRT, atau aset gratis dengan popup download",
    icon: "Sparkles",
    accent: "from-indigo-500/20 to-purple-500/10 border-indigo-500/30 text-indigo-400",
    template: {
      title: "Preset Warna & LUTs Pack Gratis",
      url: "#download-asset",
      subtitle: "Unduh file template secara instan",
      price: "FREE",
      originalPrice: "Rp 150.000",
      fileType: "ZIP • 35 MB",
      downloadUrl: "https://example.com/asset-download.zip",
      description: "Aset video editing berkualitas tinggi gratis untuk kebutuhan kreatif.",
      tags: ["Free Download", "High Quality"],
    },
  },
  {
    type: "video" as const,
    title: "Embed Video & Showreel",
    description: "Tampilkan video YouTube atau Vimeo langsung di halaman bio",
    icon: "PlayCircle",
    accent: "from-rose-500/20 to-orange-500/10 border-rose-500/30 text-rose-400",
    template: {
      title: "Video Showreel Terbaru",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      videoProvider: "youtube" as const,
      videoAspectRatio: "16:9" as const,
      subtitle: "Klik untuk memutar video langsung",
    },
  },
  {
    type: "header" as const,
    title: "Section Header",
    description: "Bagi halaman bio dengan judul kategori dan pembatas visual",
    icon: "Heading",
    accent: "from-amber-500/20 to-yellow-500/10 border-amber-500/30 text-amber-400",
    template: {
      title: "🔥 KATEGORI POPULER",
      headerStyle: "accent" as const,
    },
  },
];
